### ISSUE TITLE
[FEATURE] Update Library

### ISSUE THREAD

**Issue by derysudrajat** [derysudrajat/math-view#10]
- [x] Upgrade AGP to version 7+
- [x] Kotlin to version 1.7.0+
- [x] androidx.core:core-ktx to 1.9.0+
- [x] androidx.appcompat:appcompat to 1.5.0+
- [x] com.google.android.material:material to 1.6.0+

**Comment by DeKaN** [comment]
Hi, can I take this issue?

**Comment by derysudrajat** [comment]
Sure, I'll wait your pull request
